# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'okno.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 26))
        self.menubar.setObjectName("menubar")
        self.menuSoubor = QtWidgets.QMenu(self.menubar)
        self.menuSoubor.setObjectName("menuSoubor")
        self.menuImport = QtWidgets.QMenu(self.menuSoubor)
        self.menuImport.setObjectName("menuImport")
        self.menuV_po_ty = QtWidgets.QMenu(self.menubar)
        self.menuV_po_ty.setObjectName("menuV_po_ty")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.importSDR = QtWidgets.QAction(MainWindow)
        self.importSDR.setObjectName("importSDR")
        self.importTXT = QtWidgets.QAction(MainWindow)
        self.importTXT.setObjectName("importTXT")
        self.rajon = QtWidgets.QAction(MainWindow)
        self.rajon.setObjectName("rajon")
        self.smernikdelka = QtWidgets.QAction(MainWindow)
        self.smernikdelka.setObjectName("smernikdelka")
        self.menuSoubor.addAction(self.menuImport.menuAction())
        self.menuV_po_ty.addAction(self.rajon)
        self.menuV_po_ty.addAction(self.smernikdelka)
        self.menubar.addAction(self.menuSoubor.menuAction())
        self.menubar.addAction(self.menuV_po_ty.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuSoubor.setTitle(_translate("MainWindow", "Soubor"))
        self.menuImport.setTitle(_translate("MainWindow", "Nový"))
        self.menuV_po_ty.setTitle(_translate("MainWindow", "Výpočty"))
        self.importSDR.setText(_translate("MainWindow", "Měření \'.sdr\'"))
        self.importTXT.setText(_translate("MainWindow", "Souřadnice \'.txt\'"))
        self.rajon.setText(_translate("MainWindow", "Rajón"))
        self.smernikdelka.setText(_translate("MainWindow", "Délka a směrník"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
