# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rajon_hromadne.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Rajon_hromadne(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 130)
        Dialog.setWindowIcon(QtGui.QIcon('foto.jpg'))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 80, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.stanovisko = QtWidgets.QTextEdit(Dialog)
        self.stanovisko.setGeometry(QtCore.QRect(130, 20, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stanovisko.setFont(font)
        self.stanovisko.setObjectName("stanovisko")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Vypocet = QtWidgets.QPushButton(Dialog)
        self.Vypocet.setGeometry(QtCore.QRect(110, 80, 131, 28))
        self.Vypocet.setObjectName("Vypocet")
        self.protokol = QtWidgets.QPushButton(Dialog)
        self.protokol.setGeometry(QtCore.QRect(10, 80, 93, 28))
        self.protokol.setObjectName("protokol")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.orientace = QtWidgets.QTextEdit(Dialog)
        self.orientace.setGeometry(QtCore.QRect(370, 20, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.orientace.setFont(font)
        self.orientace.setObjectName("orientace")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Stanovisko:"))
        self.Vypocet.setText(_translate("Dialog", "Výpočet a uložení"))
        self.protokol.setText(_translate("Dialog", "Protokol"))
        self.label_2.setText(_translate("Dialog", "Orientace:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Rajon_hromadne()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
