# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seznam_souradnic.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Seznam(object):
    def setupUi(self, Seznam):
        Seznam.setObjectName("Seznam")
        Seznam.resize(677, 583)
        Seznam.setWindowIcon(QtGui.QIcon('foto.jpg'))
        self.layoutWidget = QtWidgets.QWidget(Seznam)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 651, 555))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.columnView = QtWidgets.QTableView(self.layoutWidget)
        self.columnView.setObjectName("columnView")
        self.horizontalLayout.addWidget(self.columnView)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Seznam)
        QtCore.QMetaObject.connectSlotsByName(Seznam)

    def retranslateUi(self, Seznam):
        _translate = QtCore.QCoreApplication.translate
        Seznam.setWindowTitle(_translate("Seznam", "Seznam souradnic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Seznam = QtWidgets.QDialog()
    ui = Ui_Seznam()
    ui.setupUi(Seznam)
    Seznam.show()
    sys.exit(app.exec_())
