# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'volne_stanovisko.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(559, 221)
        Dialog.setWindowIcon(QtGui.QIcon('foto.jpg'))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 170, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.orientace1 = QtWidgets.QTextEdit(Dialog)
        self.orientace1.setGeometry(QtCore.QRect(130, 20, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.orientace1.setFont(font)
        self.orientace1.setObjectName("orientace1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CB = QtWidgets.QTextEdit(Dialog)
        self.CB.setGeometry(QtCore.QRect(130, 60, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CB.setFont(font)
        self.CB.setObjectName("CB")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Xova = QtWidgets.QTextEdit(Dialog)
        self.Xova.setGeometry(QtCore.QRect(130, 100, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Xova.setFont(font)
        self.Xova.setObjectName("Xova")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(350, 100, 20, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Yova = QtWidgets.QTextEdit(Dialog)
        self.Yova.setGeometry(QtCore.QRect(370, 100, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Yova.setFont(font)
        self.Yova.setObjectName("Yova")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(110, 100, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Vypocet = QtWidgets.QPushButton(Dialog)
        self.Vypocet.setGeometry(QtCore.QRect(210, 170, 93, 28))
        self.Vypocet.setObjectName("Vypocet")
        self.uloz = QtWidgets.QPushButton(Dialog)
        self.uloz.setGeometry(QtCore.QRect(110, 170, 93, 28))
        self.uloz.setObjectName("uloz")
        self.protokol = QtWidgets.QPushButton(Dialog)
        self.protokol.setGeometry(QtCore.QRect(10, 170, 93, 28))
        self.protokol.setObjectName("protokol")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.orientace2 = QtWidgets.QTextEdit(Dialog)
        self.orientace2.setGeometry(QtCore.QRect(370, 20, 121, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.orientace2.setFont(font)
        self.orientace2.setObjectName("orientace2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Volné stanovisko"))
        self.label.setText(_translate("Dialog", "Orientace 1:"))
        self.label_5.setText(_translate("Dialog", "Stanovisko:"))
        self.label_6.setText(_translate("Dialog", "Y:"))
        self.label_7.setText(_translate("Dialog", "X:"))
        self.Vypocet.setText(_translate("Dialog", "Výpočet"))
        self.uloz.setText(_translate("Dialog", "Ulož bod"))
        self.protokol.setText(_translate("Dialog", "Protokol"))
        self.label_2.setText(_translate("Dialog", "Orientace 2:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
